services:
  #base de datos mariadb
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    ports:
      - '3306:3306'
    expose:
      - '3306'
    env_file:
      - ".env"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  #framework laravel
  myapp:
    tty: true
    image: docker.io/bitnami/laravel:10
    labels:
      kompose.service.type: nodeport
    ports:
      - '8000:8000'
    env_file:
      - ".env"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=${MARIADB_USER}
      - DB_DATABASE=${MARIADB_DATABASE}
      - DB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - './proyecto_dj:/app'
    depends_on:
      - mariadb

  #servidor ftp
  pure-ftp:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"  # Active mode FTP ports
    environment:
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_HOST=mariadb
      - MYSQL_DB=ftp_db
      - PURE_FTPD_USERS_DB=ftp_users
      - FTP_USER_ALIAS_FIELD=alias
      - FTP_USER_PASSWORD_FIELD=password
      - FTP_USER_HOME_FIELD=directorio_raiz
      - FTP_USER_STATUS_FIELD=estado
      - FTP_USER_TYPE_FIELD=tipo_user
    volumes:
      - './ftp/ftp_data:/home/ftpusers'
    depends_on:
      - mariadb